### ISSUE TITLE
InterfaceError: wlan1     Interface doesn't support scanning. // Werkzeug Debugger

### ISSUE THREAD

**Issue by nunziofiore** [WebMaestroFr/rpi-roam-webapp#7]
Hi
 when I click con CONNECT in the webapp after  setting the wifi I have this error in console:

InterfaceError: wlan1     Interface doesn't support scanning. // Werkzeug Debugger

**Comment by WebMaestroFr** [comment]
Hi !
This is most probably a problem with your second interface, your USB WiFi adapter.
If it can be used as an AP, try to swap _wlan1_ as "Access Point Interface" and _wlan0_ as "Adapter Interface" and see if you get any luck.

**Comment by nunziofiore** [comment]
I have an rpi3, no usb adapter so. But the only one with rpi3. So now I understood, sorry. I have to use the adapter for access point and the plugged in wif of rpi3 as wifi main access. Right?

**Comment by nunziofiore** [comment]
Ok I tried with a wifi adapter and I understood better all. It run and it's ok.
Great job.
Now I study this http://www.raspberryconnect.com/network/item/315-rpi3-auto-wifi-hotspot-if-no-internet and try to mix your solution and their. In this way we can use only the on board wifi to make all the work. 
Thank yuo
